# Generated by Django 3.1.4 on 2021-01-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
