# Generated by Django 3.1.4 on 2021-01-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20210102_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=4)),
                ('serial', models.SmallIntegerField()),
                ('type', models.CharField(max_length=10)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.department')),
            ],
        ),
    ]
