# Generated by Django 3.1.4 on 2021-01-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_auto_20210106_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end',
            field=models.DateTimeField(verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='term',
            name='start',
            field=models.DateTimeField(verbose_name='开始日期'),
        ),
    ]
