# Generated by Django 3.1.4 on 2021-01-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pinx', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('secode', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('gender', models.SmallIntegerField()),
                ('graduate', models.CharField(max_length=100)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
