# Generated by Django 3.1.4 on 2021-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.SmallIntegerField(choices=[('1', '女'), (2, '男')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='secode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[('ch', '教师'), ('admin', '管理员'), ('back', '后勤人员')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
