# Generated by Django 3.1.4 on 2021-01-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_auto_20210103_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, choices=[('yw', '语文'), ('ds', '数学'), ('yy', '英语'), ('xx', '信息'), ('ty', '体育')], max_length=20, null=True),
        ),
    ]
