# Generated by Django 3.1.4 on 2021-01-05 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_auto_20210103_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherimport',
            name='file',
            field=models.FileField(upload_to='excel', validators=[django.core.validators.FileExtensionValidator(['xls', 'xlsx'], message='必须为excel文件，后缀名为xls,xlsx!')]),
        ),
    ]
